// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9UXjDxnBeAL6Fm7ScJ1Lcu9lvDo21ckY',
    appId: '1:428817663529:web:aed2bc8c62c974b3cd7e38',
    messagingSenderId: '428817663529',
    projectId: 'flutter-bookshelf-app',
    authDomain: 'flutter-bookshelf-app.firebaseapp.com',
    storageBucket: 'flutter-bookshelf-app.firebasestorage.app',
    measurementId: 'G-J32V3JH9G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsthj53aQI7vowODUVkPgK2PbKOPvvPPY',
    appId: '1:428817663529:android:f10fcc1f7e74406bcd7e38',
    messagingSenderId: '428817663529',
    projectId: 'flutter-bookshelf-app',
    storageBucket: 'flutter-bookshelf-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLYw_hnP1_9toEEbBbUWbwBy2jSUh0m8E',
    appId: '1:428817663529:ios:c979b65239f89287cd7e38',
    messagingSenderId: '428817663529',
    projectId: 'flutter-bookshelf-app',
    storageBucket: 'flutter-bookshelf-app.firebasestorage.app',
    iosBundleId: 'com.example.bookShelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLYw_hnP1_9toEEbBbUWbwBy2jSUh0m8E',
    appId: '1:428817663529:ios:c979b65239f89287cd7e38',
    messagingSenderId: '428817663529',
    projectId: 'flutter-bookshelf-app',
    storageBucket: 'flutter-bookshelf-app.firebasestorage.app',
    iosBundleId: 'com.example.bookShelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9UXjDxnBeAL6Fm7ScJ1Lcu9lvDo21ckY',
    appId: '1:428817663529:web:eabba291a63e019ccd7e38',
    messagingSenderId: '428817663529',
    projectId: 'flutter-bookshelf-app',
    authDomain: 'flutter-bookshelf-app.firebaseapp.com',
    storageBucket: 'flutter-bookshelf-app.firebasestorage.app',
    measurementId: 'G-DWD7HJXV5T',
  );
}
